---

- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  post_tasks:
    - name: "wait 1 min to allow for server to run"
      pause:
        minutes: 1
  roles:
    - deploy