- name: Copy Files Into Server
  copy:
    src: ~/project/
    dest: /home/ubuntu/

- name: Download Go
  become: yes
  shell: |
    cd /home/ubuntu/ 
    wget https://storage.googleapis.com/golang/go1.13.9.linux-amd64.tar.gz
    tar -C /usr/local -xzf go1.13.9.linux-amd64.tar.gz

- name: Configure Go
  become: yes
  shell: |
    echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile
    echo 'export GOPATH=$HOME/gopath' >> /etc/profile

- name: Source Go
  become: yes
  shell: |
    source /etc/profile

- name: Build Executable
  become: yes
  shell: |
    cd /home/ubuntu/
    go build main.go 

- name: Start Server
  become: yes
  shell: |
    cd /home/ubuntu/ && 
    chmod +x main 
    ./main