version: 2.1

jobs:
  build-code:
    docker:
      - image: cimg/go:1.19.4
    steps:
      - checkout  
      - run:
        name: build-code
        command: |
          cd ~/project/
          go build main.go

workflows:
  default:
    jobs:
      - build-code
