# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  destroy-environment:
    description: Destroy cloudformation stacks given a workflow ID.
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            if ! command -v aws &> /dev/null
            then
              if ! command -v curl &> /dev/null
              then
                apk --no-cache add curl
              fi
              alias python="python3"
              curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
              unzip awscli-bundle.zip
              ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
            fi
            aws cloudformation delete-stack --stack-name golang-cms-${CIRCLE_WORKFLOW_ID:0:7}

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-code:
    docker:
      - image: cimg/go:1.19.4
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: "Build Code"
          command: "cd ~/project/ && go build main.go"
      - save_cache:
          paths: [/]
          key: backend-build
  
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar
          command: |
            yum -y install tar
      - run:
          name: Install gzip
          command: |
            yum -y install gzip
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/cms-backend.yml \
              --tags project=golang-cms \
              --stack-name "golang-cms-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters Name=tag:Name,Values=cms-backend-${CIRCLE_WORKFLOW_ID:0:7} \
            --output text >> .circleci/ansible/inventory.txt
      - run:
          name: Contents of inventory.txt
          command: |
            cat .circleci/ansible/inventory.txt
      - persist_to_workspace:
          root: .circleci/ansible
          paths:
            - inventory.txt
      # Here's where you will add some code to rollback on failure
      - destroy-environment

  configure-infrastructure:
    docker:
      # Docker image here that supports Ansible
      - image: python:3.9.16
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [ "e1:74:49:8f:30:32:ae:f5:fc:a3:69:be:19:69:08:43" ]
      - attach_workspace:
          at: /tmp/.circleci/ansible
      - run:
          name: Install dependencies
          command: |
            apt-get update -y
            apt install ansible -y
      - run:
          name: Configure server
          command: |
            ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook -i /tmp/.circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
      - destroy-environment

  deploy-code:
    docker:
      - image: python:3.9.16
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [ "e1:74:49:8f:30:32:ae:f5:fc:a3:69:be:19:69:08:43" ]
      - attach_workspace:
          at: /tmp/.circleci/ansible
      - restore_cache:
          keys: [ backend-build ]
      - run:
          name: Install dependencies
          command: |
            apt-get update -y
            apt install ansible -y
      - run:
          name: Contents of inventory.txt
          command: |
            cat /tmp/.circleci/ansible/inventory.txt
      - run:
          name: Deploy backend
          command: |
            ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook -i /tmp/.circleci/ansible/inventory.txt .circleci/ansible/deploy-backend.yml
      - destroy-environment
          
workflows:
  default:
    jobs:
      - build-code
      - deploy-infrastructure:
          requires: [build-code]
      - configure-infrastructure:
          requires: [deploy-infrastructure]
      - deploy-code:
          requires: [configure-infrastructure]
